server:
  error:
    include-stacktrace:  always
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/anime?useSSL=false
    #username: root
    #password: root
    url: jdbc:sqlserver://brjgsd312446;instanceName=SQLEXPRESS;databaseName=anime
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: weg1234@
    username: sa
  jpa:
  
    hibernate:
      ddl-auto: update

logging:  level:    org:
      hibernate:
        SQL: DEBUG
        type: 
          descriptor:
            sql:
              BasicBinder: TRACE
            